version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.11.1

jobs:
  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Plan deployment
          # command: echo "Plan deployment step" # ADAPTE
      - run:
          name: Perform deployment
          command: |
            rsync -avz --delete ./ $USER@$SERVER:$DEPLOY_PATH
      - run:
          name: Update planned deployment to running
          # command: echo "Update status to running" # ADAPTE
      - run:
          name: Validate deployment
          # command: npm test # ADAPTE
      - run:
          name: Update planned deployment to SUCCESS
          command: echo "Update status to SUCCESS"
          when: on_success
      - run:
          name: Update planned deployment to FAILED
          command: |
            if [ -f failure_reason.env ]; then
              source failure_reason.env
            fi
            echo "Update status to FAILED: $FAILURE_REASON"
          when: on_fail
  cancel-deploy:
    executor: node-executor
    steps:
      - run:
          name: Update planned release to CANCELED
          command: echo "Update status to CANCELED"

workflows:
  deploy-workflow:
    jobs:
      - deploy
      - cancel-deploy:
          requires:
            - deploy:
                - canceled
