version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - add_ssh_keys:
          fingerprints:
            - "your-ssh-key-fingerprint"
      - run:
          name: Deploy to Server
          command: |
            ssh user@your-server-ip 'bash -s' < deploy_script.sh

workflows:
  deploy-workflow:
    jobs:
      - deploy
